name: Build and Test Windows

#------------------------------------------------
# Workflow Triggers
#------------------------------------------------
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#------------------------------------------------
# Environment Variables
#------------------------------------------------
env:
  MAIN_PROJECT_NAME: ${{ github.event.repository.name }}
  BUILD_TYPE: Debug
  BUILD_TARGET_TYPE: static_library
  BUILD_TEST_PROJECT: true
  THIRD_PARTY_INCLUDE_DIR: ${{ github.workspace }}\\ThirdPartyDir
  QT_VERSION: "6.8.0"

#------------------------------------------------
# Workflow jobs
#------------------------------------------------
jobs:
  build_and_test:
    name: Build and Test on Windows Latest
    runs-on: windows-latest
    steps:
      # Checkout the repository and submodules
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Prepare third-party directory
      - name: Prepare third-party directory
        run: mkdir ${{ env.THIRD_PARTY_INCLUDE_DIR }}

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          base-url: 'https://download.qt.io/official_releases/'

      # Install CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '4.1.1'

      # Configure CMake
      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
                -DCMAKE_PREFIX_PATH="C:\Qt\${{ env.QT_VERSION }}\msvc2022_64" `
                -DMAIN_PROJECT_NAME=${{ env.MAIN_PROJECT_NAME }} `
                -D${{ env.MAIN_PROJECT_NAME }}_BUILD_TARGET_TYPE=${{ env.BUILD_TARGET_TYPE }} `
                -D${{ env.MAIN_PROJECT_NAME }}_BUILD_TEST_PROJECT=${{ env.BUILD_TEST_PROJECT }} `
                -DTHIRD_PARTY_INCLUDE_DIR=${{ env.THIRD_PARTY_INCLUDE_DIR }}

      # Build the project
      - name: Build
        run: |
          cd build
          cmake --build . --config ${{ env.BUILD_TYPE }}

      # Run Tests
      - name: Run Tests
        env:
          PATH: C:\Qt\${{ env.QT_VERSION }}\msvc2022_64\bin;${{ env.PATH }}
        run: |
          .\build\QT_Project_Tests\${{ env.BUILD_TYPE }}\${{ env.MAIN_PROJECT_NAME }}_Tests.exe
